[package]
name = "windmark"
version = "0.0.0"
edition = "2021"
description = "Simple and highly performant Gemini server framework"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
