# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]
private = true

[tasks.check]
command = "cargo"
args = ["check"]
private = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]
private = true

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]

[tasks.genkey]
command = "openssl"
args = [
  "req",
  "-new",
  "-subj",
  "/CN=localhost",
  "-x509",
  "-newkey",
  "ec",
  "-pkeyopt",
  "ec_paramgen_curve:prime256v1",
  "-days",
  "365",
  "-nodes",
  "-out",
  "windmark_public.pem",
  "-keyout",
  "windmark_private.pem",
  "-inform",
  "pem",
]

[tasks.docs]
workspace = false
toolchain = "nightly"
command = "cargo"
args = ["doc", "--open", "--no-deps"]

[tasks.example]
command = "cargo"
args = ["run", "--example", "${@}", "--all-features"]
