[tasks.fmt]
args = ["fmt"]
command = "cargo"
toolchain = "nightly"

[tasks.check]
args = ["check", "--no-default-features", "--features", "logger,auto-deduce-mime,response-macros,${@}"]
command = "cargo"
toolchain = "nightly"

[tasks.clippy]
args = ["clippy", "--no-default-features", "--features", "logger,auto-deduce-mime,response-macros,${@}"]
command = "cargo"
toolchain = "nightly"

[tasks.checkf]
script = '''
#!@shell

cargo make fmt
cargo make check tokio
cargo make check async-std
'''

[tasks.checkfc]
script = '''
#!@shell

cargo make fmt
cargo make check tokio
cargo make check async-std
cargo make clippy tokio
cargo make clippy async-std
'''

[tasks.genkey]
command = "openssl"
args = [
  "req",
  "-new",
  "-subj",
  "/CN=localhost",
  "-x509",
  "-newkey",
  "ec",
  "-pkeyopt",
  "ec_paramgen_curve:prime256v1",
  "-days",
  "365",
  "-nodes",
  "-out",
  "windmark_public.pem",
  "-keyout",
  "windmark_private.pem",
  "-inform",
  "pem",
]

[tasks.docs]
workspace = false
toolchain = "nightly"
command = "cargo"
args = ["doc", "--open", "--no-deps"]

[tasks.example]
script = '''
#!@duckscript

if is_empty ${2}
  exec cargo run --example ${1} --no-default-features --features logger,auto-deduce-mime,response-macros,tokio
else
  exec cargo run --example ${1} --no-default-features --features logger,auto-deduce-mime,response-macros,${2}
end
'''
