[package]
name = "windmark-compatibility-consumer"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[features]
tokio = ["windmark/tokio", "dep:tokio"]
async-std = ["windmark/async-std"]
auto-deduce-mime = []

[dependencies]
windmark = { path = "../..", default-features = false, features = ["response-macros", "auto-deduce-mime"] }
rossweisse = { path = "../../rossweisse" }
async-trait = "0.1.68"
tokio = { version = "1.52.3", optional = true, features = ["macros", "rt"] }
