name: Check ✅

on:
  workflow_dispatch:
  push:
    paths:
      - "**"
  pull_request:
    paths:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v3

      - name: Toolchain 🧰
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Check ✅
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: check
          args: --verbose

      - name: Test 🧪
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: test
          args: --verbose --features auto-deduce-mime,response-macros
