name: Check ✅

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v4

      - name: Toolchain 🧰
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Just 📋
        uses: extractions/setup-just@v2

      - name: Format, check, and lint ✅
        run: just checkfc

      - name: Verify formatting 🎨
        run: git diff --exit-code

      - name: Test 🧪
        run: |
          just test tokio
          just test async-std
